### ISSUE TITLE
Need to decode special characters into filename

### ISSUE THREAD

**Issue by timbl** [bergos/file-fetch#1]
```
const pathname = url.parse(iri).pathname
```
looks as though it won't translate between a %20 in a URL and a space in a filename, which it should, because (a) you need to encode funny characters in filenames and (b) that's the way everyone has been doing it.  

See eg https://github.com/solid/node-solid-server/blob/master/lib/utils.js#L73

**Comment by bergos** [comment]
Fix with commit https://github.com/bergos/file-fetch/commit/f5e741f93951ac86426c45b60a76179ba3074472

**Comment by brettz9** [comment]
Can this be closed then?
