### ISSUE TITLE
README example uses non-spec compliant file:// urls

### ISSUE THREAD

**Issue by Bluebie** [bergos/file-fetch#17]
`file://dir/dir/filename` isn't compliant with the URL or file: specs, because URLs have a hostname field. Correct `file://` urls take the form of `file://hostname/rootdir/subdir/file`, and in general use, hostname is a zero length string, implying the local host, so end up looking like the thing you see often in web browsers: `file:///rootdir/subdir/file` - note the three slashes.

The format you use in your examples is supported in most web browsers, as a quirk parsing, but it's really messy because it looks like a URL but doesn't store data like a URL and can't be correctly parsed with URL parser algorithms if you omit the third slash.

**Comment by bergos** [comment]
I don't remember the details, but I think it was a legacy issue related to the requirement to support relative paths. I guess it was `url.parse()`, that only worked with two slashes + relative path. Now we have the URN support for that use case.

You are right, we should use correct URLs with three slashes for the absolute path use case.

I will check if the current code can handle `file:///` URLs. If that is not the case I will add support for it. I will keep support for `file://` URLs at least till the next major version. Once I validated that the code works with correct URLs, I will update the README.

**Comment by bergos** [comment]
fixed in #20 an released as v2.0.0
